apiVersion: v1
kind: ReplicationController
metadata:
   name: myrc1
spec:
   replicas: 5
   selector:
         app: rc
   template:
          metadata:
              name: "pod1"
              labels:
                   app: rc
          spec:
                   containers:
                   -    name: "con1"
                        image: "centos:7"
                        stdin: True
                        tty: True
        
