apiVersion: v1
kind: PersistentVolume
metadata:
    name: mypv
spec:
    storageClassName: ""
    capacity:
        storage: 12Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/data-backup"