apiVersion: v1
kind: PersistentVolumeClaim
metadata:
      name: mpc
spec:
      storageClassName: ""
      accessModes:
      -  ReadWriteOnce
      resources:
           requests:
                storage: 12Gi